// dispatcher.hpp, created by Andrew Gossen.

// ----
// 
// This is the core dispatch system for the backtesting engine
// Holds a dispatch class, which owns the central event queue using a fixed-capacity
// ringbuffer, and dispatches events to the appropraite handler function (in the pipeline folder)

// Used to store events in a ring-buffer for later dispatching. Events are dispatched in this order : 
    // HANDLER FUNCTION | EVENT TAKEN -> EVENT GIVEN 
    // StrategyHandler - ( MarketEvent -> SignalEvent)
    // RiskHandler - ( SignalEvent -> OrderEvent )
    // ExcecutionHandler - (OrderEvent -> FillEvent )
    // PortfolioHandler - ( FillEvent -> Final action ) 

// --- 

#pragma once 
#include <vector>
#include <functional>
#include <utility>
#include <deque>
#include <iostream>

#include "events/events.hpp"
#include "events/ring_buffer.hpp"
#include "data/market_state.hpp"
#include "backtesting/backtesting.hpp"
#include "pipeline/strategy_handler.hpp"
#include "pipeline/risk_handler.hpp"
#include "pipeline/portfolio_handler.hpp"
#include "pipeline/excecution_handler.hpp"
#include "pipeline/trace_handler.hpp"
#include "pipeline/report_handler.hpp"
#include "pipeline/stop_manager.hpp"

namespace events{

template <std::size_t capacity>
class Dispatcher{

    public:

    Dispatcher(Excecution& exce,Strategy& strat,trd::MarketState& marketState,Portfolio& portfolio,trd::Result& result) : 
    m_handlerStrat(strat,*this),
    m_handlerRisk(portfolio,marketState,*this),
    m_handlerExce(exce,marketState,*this),
    m_handlerPort(portfolio),
    m_handlerReport(marketState,portfolio,result),
    m_handlerStop(*this,portfolio,marketState)
    {
        // Set the risk handler
        m_handlerRisk.current=TrivialRisk;
    }

    using queue=RingBuffer<Event,capacity>;

    bool schedule(Event&& ev){ // Schedule an event, i.e. add to the ring-buffer to be dispatched 
        return m_queue.push(std::move(ev));
    }

    void run(){  // Dispatch all events in the ringbuffer ( Calling an overloaded 'on' function )
        Event e;
        while (m_queue.pop(e)){
            dispatch(e);
        }
    }

    // Overload 'on' functions to run the appropriate handler 

    void on(const events::MarketEvent& ev) { // Ran every bar 
        m_handlerStrat.on(ev); m_handlerReport.setEquity();
        m_handlerStop.on(ev);
    } 

    // SignalEvent generated by strategy handler 
    void on(const events::SignalEvent& ev) { m_handlerRisk.current(m_handlerRisk,ev); } 
    // OrderEvent generated by risk handler
    void on(const events::OrderEvent& ev) { m_handlerExce.on(ev); }  
    // FillEvent generated by excecution handler 
    void on(const events::FillEvent& ev) { m_handlerPort.on(ev); m_handlerReport.on(ev); m_handlerStop.on(ev); } 

    // StopEvents for the risk handler, used to close a position when market conditions are met 
    void on(const events::StopFillEvent& ev) { m_handlerExce.on(ev); }
    void on(const events::StopPlanEvent ev) { m_handlerStop.on(ev); }

    // Getters 
    ReportHandler getReportHandler() const { return m_handlerReport; } 

    private: 

    void dispatch(Event& e){ // Will dispatch an event, i.e. run the appropriate handler through overload resolution 
        std::visit( // Pass the variant's contained value directly into lambda 
            [this](auto const& event){
                this->on(event);
            },
            e
        );
    }

    queue m_queue{};

    StrategyHandler<Dispatcher> m_handlerStrat;
    RiskData<Dispatcher> m_handlerRisk;
    ExcecutionHandler<Dispatcher> m_handlerExce;
    PortfolioHandler m_handlerPort;
    ReportHandler m_handlerReport;
    StopHandler<Dispatcher> m_handlerStop;
    

};

}